on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Lint markdown
        run: npx markdownlint-cli2 "*.md" "#MAINTAINERS.md"
